trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)

stages:
- stage: Build
  displayName: BuildStageDisplayName
  jobs:
  - job: 'django_basic'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
      maxParallel: 1
    steps:
    - task: ServiceNow-DevOps-Build-Sonar-Registration@1
      inputs:
        connectedServiceName: 'empdevhafsa-SonarIntegration-ServiceNow DevOps Service Connection'
        sonarProjectKey: 'hafsataneem_SonarCloud'
        sonarInstanceUrl: 'https://sonarcloud.io'
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - script: |
        python -m pip install --upgrade pip
        pip install -r django-basic/requirements.txt
      displayName: 'Install dependencies'

    - script: |
        pip install pytest-django
        cd django-basic/azuredemo
        pytest --junitxml=../../reports/django-basic.xml
      displayName: 'Run tests'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'reports/django-basic.xml'
        testRunTitle: '$(Agent.JobName)'
      condition: succeededOrFailed()
    
- stage: 
  displayName: 
  jobs:
  - job: 'django_basic'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
      maxParallel: 1
    steps:
    - task: ServiceNow-DevOps-Build-Sonar-Registration@1
      inputs:
        connectedServiceName: 'empdevhafsa-SonarIntegration-ServiceNow DevOps Service Connection'
        sonarProjectKey: 'hafsataneem_SonarCloud'
        sonarInstanceUrl: 'https://sonarcloud.io'
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - script: |
        python -m pip install --upgrade pip
        pip install -r django-basic/requirements.txt
      displayName: 'Install dependencies'

    - script: |
        pip install pytest-django
        cd django-basic/azuredemo
        pytest --junitxml=../../reports/django-basic.xml
      displayName: 'Run tests'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'reports/django-basic.xml'
        testRunTitle: '$(Agent.JobName)'
      condition: succeededOrFailed()
- stage: 
  displayName: MatrixStageDisplayName
  jobs:
  - job: 'django_basic'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
      maxParallel: 1
    steps:
    - task: ServiceNow-DevOps-Build-Sonar-Registration@1
      inputs:
        connectedServiceName: 'empdevhafsa-SonarIntegration-ServiceNow DevOps Service Connection'
        sonarProjectKey: 'hafsataneem_SonarCloud'
        sonarInstanceUrl: 'https://sonarcloud.io'
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - script: |
        python -m pip install --upgrade pip
        pip install -r django-basic/requirements.txt
      displayName: 'Install dependencies'

    - script: |
        pip install pytest-django
        cd django-basic/azuredemo
        pytest --junitxml=../../reports/django-basic.xml
      displayName: 'Run tests'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'reports/django-basic.xml'
        testRunTitle: '$(Agent.JobName)'
      condition: succeededOrFailed()


- stage:
  displayName: NoNameStageDisplayName
  jobs:
  - job: 'StageLess'
    displayName: displayNameForJobStageLess
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'
    - task: ServiceNow-DevOps-Build-Sonar-Registration@1
      inputs:
        connectedServiceName: 'empdevhafsa-SonarIntegration-ServiceNow DevOps Service Connection'
        sonarProjectKey: 'hafsataneem_SonarCloud'
        sonarInstanceUrl: 'https://sonarcloud.io'
- stage:
  displayName: NoNameStageDisplayName
  jobs:
  - job: 'StageLess'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'
    - task: ServiceNow-DevOps-Build-Sonar-Registration@1
      inputs:
        connectedServiceName: 'empdevhafsa-SonarIntegration-ServiceNow DevOps Service Connection'
        sonarProjectKey: 'hafsataneem_SonarCloud'
        sonarInstanceUrl: 'https://sonarcloud.io'
- stage: 
  displayName:
  jobs:
  - job:
    displayName:
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'
    - task: ServiceNow-DevOps-Build-Sonar-Registration@1
      inputs:
        connectedServiceName: 'empdevhafsa-SonarIntegration-ServiceNow DevOps Service Connection'
        sonarProjectKey: 'hafsataneem_SonarCloud'
        sonarInstanceUrl: 'https://sonarcloud.io'
    - task: ServiceNow-DevOps-Build-Sonar-Registration@1
      inputs:
        connectedServiceName: 'empdevhafsa-SonarIntegration-ServiceNow DevOps Service Connection'
        sonarProjectKey: 'hafsataneem_SonarCloud'
        sonarInstanceUrl: 'https://sonarcloud.io'
  