trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)

stages:
- stage: Build
  jobs:
  - job: 'django_basic'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
      maxParallel: 1
    steps:
    - task: ServiceNow-DevOps-Agent-Job-Notification@1
      inputs:
        connectedServiceName: 'newCon'
        Phase: 'STARTED'
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - script: |
        python -m pip install --upgrade pip
        pip install -r django-basic/requirements.txt
      displayName: 'Install dependencies'

    - script: |
        pip install pytest-django
        cd django-basic/azuredemo
        pytest --junitxml=../../reports/django-basic.xml
      displayName: 'Run tests'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'reports/django-basic.xml'
        testRunTitle: '$(Agent.JobName)'
      condition: succeededOrFailed()
    - task: ServiceNow-DevOps-Agent-Job-Notification@1
      inputs:
          connectedServiceName: 'newCon'
          Phase: 'COMPLETED'
